#!/bin/vbash
# shellcheck disable=all

set firewall ipv4 forward filter default-action 'accept'
set firewall ipv4 forward filter rule 1 action 'accept'
set firewall ipv4 forward filter rule 1 state established 'enable'
set firewall ipv4 forward filter rule 2 action 'drop'
set firewall ipv4 forward filter rule 2 state invalid 'enable'
set firewall ipv4 forward filter rule 3 action 'accept'
set firewall ipv4 forward filter rule 3 state related 'enable'
set firewall ipv4 forward filter rule 101 action 'accept'
set firewall ipv4 forward filter rule 101 inbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 101 outbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 106 action 'jump'
set firewall ipv4 forward filter rule 106 inbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 106 jump-target 'homelab-guest'
set firewall ipv4 forward filter rule 106 outbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 111 action 'jump'
set firewall ipv4 forward filter rule 111 inbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 111 jump-target 'iot-guest'
set firewall ipv4 forward filter rule 111 outbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 116 action 'jump'
set firewall ipv4 forward filter rule 116 inbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 116 jump-target 'lan-guest'
set firewall ipv4 forward filter rule 116 outbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 121 action 'jump'
set firewall ipv4 forward filter rule 121 inbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 121 jump-target 'servers-guest'
set firewall ipv4 forward filter rule 121 outbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 126 action 'jump'
set firewall ipv4 forward filter rule 126 inbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 126 jump-target 'services-guest'
set firewall ipv4 forward filter rule 126 outbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 131 action 'jump'
set firewall ipv4 forward filter rule 131 inbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 131 jump-target 'staging-guest'
set firewall ipv4 forward filter rule 131 outbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 136 action 'jump'
set firewall ipv4 forward filter rule 136 inbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 136 jump-target 'trusted-guest'
set firewall ipv4 forward filter rule 136 outbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 141 action 'jump'
set firewall ipv4 forward filter rule 141 inbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 141 jump-target 'wan-guest'
set firewall ipv4 forward filter rule 141 outbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 146 action 'drop'
set firewall ipv4 forward filter rule 146 description 'zone_guest default-action'
set firewall ipv4 forward filter rule 146 outbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 151 action 'accept'
set firewall ipv4 forward filter rule 151 inbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 151 outbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 156 action 'jump'
set firewall ipv4 forward filter rule 156 inbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 156 jump-target 'guest-homelab'
set firewall ipv4 forward filter rule 156 outbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 161 action 'jump'
set firewall ipv4 forward filter rule 161 inbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 161 jump-target 'iot-homelab'
set firewall ipv4 forward filter rule 161 outbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 166 action 'jump'
set firewall ipv4 forward filter rule 166 inbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 166 jump-target 'lan-homelab'
set firewall ipv4 forward filter rule 166 outbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 171 action 'jump'
set firewall ipv4 forward filter rule 171 inbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 171 jump-target 'servers-homelab'
set firewall ipv4 forward filter rule 171 outbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 176 action 'jump'
set firewall ipv4 forward filter rule 176 inbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 176 jump-target 'services-homelab'
set firewall ipv4 forward filter rule 176 outbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 181 action 'jump'
set firewall ipv4 forward filter rule 181 inbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 181 jump-target 'staging-homelab'
set firewall ipv4 forward filter rule 181 outbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 186 action 'jump'
set firewall ipv4 forward filter rule 186 inbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 186 jump-target 'trusted-homelab'
set firewall ipv4 forward filter rule 186 outbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 191 action 'jump'
set firewall ipv4 forward filter rule 191 inbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 191 jump-target 'wan-homelab'
set firewall ipv4 forward filter rule 191 outbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 196 action 'drop'
set firewall ipv4 forward filter rule 196 description 'zone_homelab default-action'
set firewall ipv4 forward filter rule 196 outbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 201 action 'accept'
set firewall ipv4 forward filter rule 201 inbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 201 outbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 206 action 'jump'
set firewall ipv4 forward filter rule 206 inbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 206 jump-target 'guest-iot'
set firewall ipv4 forward filter rule 206 outbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 211 action 'jump'
set firewall ipv4 forward filter rule 211 inbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 211 jump-target 'homelab-iot'
set firewall ipv4 forward filter rule 211 outbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 216 action 'jump'
set firewall ipv4 forward filter rule 216 inbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 216 jump-target 'lan-iot'
set firewall ipv4 forward filter rule 216 outbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 221 action 'jump'
set firewall ipv4 forward filter rule 221 inbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 221 jump-target 'servers-iot'
set firewall ipv4 forward filter rule 221 outbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 226 action 'jump'
set firewall ipv4 forward filter rule 226 inbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 226 jump-target 'services-iot'
set firewall ipv4 forward filter rule 226 outbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 231 action 'jump'
set firewall ipv4 forward filter rule 231 inbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 231 jump-target 'staging-iot'
set firewall ipv4 forward filter rule 231 outbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 236 action 'jump'
set firewall ipv4 forward filter rule 236 inbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 236 jump-target 'trusted-iot'
set firewall ipv4 forward filter rule 236 outbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 241 action 'jump'
set firewall ipv4 forward filter rule 241 inbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 241 jump-target 'wan-iot'
set firewall ipv4 forward filter rule 241 outbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 246 action 'drop'
set firewall ipv4 forward filter rule 246 description 'zone_iot default-action'
set firewall ipv4 forward filter rule 246 outbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 251 action 'accept'
set firewall ipv4 forward filter rule 251 inbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 251 outbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 256 action 'jump'
set firewall ipv4 forward filter rule 256 inbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 256 jump-target 'guest-lan'
set firewall ipv4 forward filter rule 256 outbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 261 action 'jump'
set firewall ipv4 forward filter rule 261 inbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 261 jump-target 'homelab-lan'
set firewall ipv4 forward filter rule 261 outbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 266 action 'jump'
set firewall ipv4 forward filter rule 266 inbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 266 jump-target 'iot-lan'
set firewall ipv4 forward filter rule 266 outbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 271 action 'jump'
set firewall ipv4 forward filter rule 271 inbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 271 jump-target 'servers-lan'
set firewall ipv4 forward filter rule 271 outbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 276 action 'jump'
set firewall ipv4 forward filter rule 276 inbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 276 jump-target 'services-lan'
set firewall ipv4 forward filter rule 276 outbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 281 action 'jump'
set firewall ipv4 forward filter rule 281 inbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 281 jump-target 'staging-lan'
set firewall ipv4 forward filter rule 281 outbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 286 action 'jump'
set firewall ipv4 forward filter rule 286 inbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 286 jump-target 'trusted-lan'
set firewall ipv4 forward filter rule 286 outbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 291 action 'jump'
set firewall ipv4 forward filter rule 291 inbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 291 jump-target 'wan-lan'
set firewall ipv4 forward filter rule 291 outbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 296 action 'drop'
set firewall ipv4 forward filter rule 296 description 'zone_lan default-action'
set firewall ipv4 forward filter rule 296 outbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 301 action 'accept'
set firewall ipv4 forward filter rule 301 inbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 301 outbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 306 action 'jump'
set firewall ipv4 forward filter rule 306 inbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 306 jump-target 'guest-servers'
set firewall ipv4 forward filter rule 306 outbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 311 action 'jump'
set firewall ipv4 forward filter rule 311 inbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 311 jump-target 'homelab-servers'
set firewall ipv4 forward filter rule 311 outbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 316 action 'jump'
set firewall ipv4 forward filter rule 316 inbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 316 jump-target 'iot-servers'
set firewall ipv4 forward filter rule 316 outbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 321 action 'jump'
set firewall ipv4 forward filter rule 321 inbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 321 jump-target 'lan-servers'
set firewall ipv4 forward filter rule 321 outbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 326 action 'jump'
set firewall ipv4 forward filter rule 326 inbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 326 jump-target 'services-servers'
set firewall ipv4 forward filter rule 326 outbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 331 action 'jump'
set firewall ipv4 forward filter rule 331 inbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 331 jump-target 'staging-servers'
set firewall ipv4 forward filter rule 331 outbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 336 action 'jump'
set firewall ipv4 forward filter rule 336 inbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 336 jump-target 'trusted-servers'
set firewall ipv4 forward filter rule 336 outbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 341 action 'jump'
set firewall ipv4 forward filter rule 341 inbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 341 jump-target 'wan-servers'
set firewall ipv4 forward filter rule 341 outbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 346 action 'drop'
set firewall ipv4 forward filter rule 346 description 'zone_servers default-action'
set firewall ipv4 forward filter rule 346 outbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 351 action 'accept'
set firewall ipv4 forward filter rule 351 inbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 351 outbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 356 action 'jump'
set firewall ipv4 forward filter rule 356 inbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 356 jump-target 'guest-services'
set firewall ipv4 forward filter rule 356 outbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 361 action 'jump'
set firewall ipv4 forward filter rule 361 inbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 361 jump-target 'homelab-services'
set firewall ipv4 forward filter rule 361 outbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 366 action 'jump'
set firewall ipv4 forward filter rule 366 inbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 366 jump-target 'iot-services'
set firewall ipv4 forward filter rule 366 outbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 371 action 'jump'
set firewall ipv4 forward filter rule 371 inbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 371 jump-target 'lan-services'
set firewall ipv4 forward filter rule 371 outbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 376 action 'jump'
set firewall ipv4 forward filter rule 376 inbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 376 jump-target 'servers-services'
set firewall ipv4 forward filter rule 376 outbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 381 action 'jump'
set firewall ipv4 forward filter rule 381 inbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 381 jump-target 'staging-services'
set firewall ipv4 forward filter rule 381 outbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 386 action 'jump'
set firewall ipv4 forward filter rule 386 inbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 386 jump-target 'trusted-services'
set firewall ipv4 forward filter rule 386 outbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 391 action 'jump'
set firewall ipv4 forward filter rule 391 inbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 391 jump-target 'wan-services'
set firewall ipv4 forward filter rule 391 outbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 396 action 'drop'
set firewall ipv4 forward filter rule 396 description 'zone_services default-action'
set firewall ipv4 forward filter rule 396 outbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 401 action 'accept'
set firewall ipv4 forward filter rule 401 inbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 401 outbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 406 action 'jump'
set firewall ipv4 forward filter rule 406 inbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 406 jump-target 'guest-staging'
set firewall ipv4 forward filter rule 406 outbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 411 action 'jump'
set firewall ipv4 forward filter rule 411 inbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 411 jump-target 'homelab-staging'
set firewall ipv4 forward filter rule 411 outbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 416 action 'jump'
set firewall ipv4 forward filter rule 416 inbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 416 jump-target 'iot-staging'
set firewall ipv4 forward filter rule 416 outbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 421 action 'jump'
set firewall ipv4 forward filter rule 421 inbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 421 jump-target 'lan-staging'
set firewall ipv4 forward filter rule 421 outbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 426 action 'jump'
set firewall ipv4 forward filter rule 426 inbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 426 jump-target 'servers-staging'
set firewall ipv4 forward filter rule 426 outbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 431 action 'jump'
set firewall ipv4 forward filter rule 431 inbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 431 jump-target 'services-staging'
set firewall ipv4 forward filter rule 431 outbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 436 action 'jump'
set firewall ipv4 forward filter rule 436 inbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 436 jump-target 'trusted-staging'
set firewall ipv4 forward filter rule 436 outbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 441 action 'jump'
set firewall ipv4 forward filter rule 441 inbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 441 jump-target 'wan-staging'
set firewall ipv4 forward filter rule 441 outbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 446 action 'drop'
set firewall ipv4 forward filter rule 446 description 'zone_staging default-action'
set firewall ipv4 forward filter rule 446 outbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 451 action 'accept'
set firewall ipv4 forward filter rule 451 inbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 451 outbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 456 action 'jump'
set firewall ipv4 forward filter rule 456 inbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 456 jump-target 'guest-trusted'
set firewall ipv4 forward filter rule 456 outbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 461 action 'jump'
set firewall ipv4 forward filter rule 461 inbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 461 jump-target 'homelab-trusted'
set firewall ipv4 forward filter rule 461 outbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 466 action 'jump'
set firewall ipv4 forward filter rule 466 inbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 466 jump-target 'iot-trusted'
set firewall ipv4 forward filter rule 466 outbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 471 action 'jump'
set firewall ipv4 forward filter rule 471 inbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 471 jump-target 'lan-trusted'
set firewall ipv4 forward filter rule 471 outbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 476 action 'jump'
set firewall ipv4 forward filter rule 476 inbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 476 jump-target 'servers-trusted'
set firewall ipv4 forward filter rule 476 outbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 481 action 'jump'
set firewall ipv4 forward filter rule 481 inbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 481 jump-target 'services-trusted'
set firewall ipv4 forward filter rule 481 outbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 486 action 'jump'
set firewall ipv4 forward filter rule 486 inbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 486 jump-target 'staging-trusted'
set firewall ipv4 forward filter rule 486 outbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 491 action 'jump'
set firewall ipv4 forward filter rule 491 inbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 491 jump-target 'wan-trusted'
set firewall ipv4 forward filter rule 491 outbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 496 action 'drop'
set firewall ipv4 forward filter rule 496 description 'zone_trusted default-action'
set firewall ipv4 forward filter rule 496 outbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 501 action 'accept'
set firewall ipv4 forward filter rule 501 inbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 501 outbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 506 action 'jump'
set firewall ipv4 forward filter rule 506 inbound-interface interface-group 'IG_guest'
set firewall ipv4 forward filter rule 506 jump-target 'guest-wan'
set firewall ipv4 forward filter rule 506 outbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 511 action 'jump'
set firewall ipv4 forward filter rule 511 inbound-interface interface-group 'IG_homelab'
set firewall ipv4 forward filter rule 511 jump-target 'homelab-wan'
set firewall ipv4 forward filter rule 511 outbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 516 action 'jump'
set firewall ipv4 forward filter rule 516 inbound-interface interface-group 'IG_iot'
set firewall ipv4 forward filter rule 516 jump-target 'iot-wan'
set firewall ipv4 forward filter rule 516 outbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 521 action 'jump'
set firewall ipv4 forward filter rule 521 inbound-interface interface-group 'IG_lan'
set firewall ipv4 forward filter rule 521 jump-target 'lan-wan'
set firewall ipv4 forward filter rule 521 outbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 526 action 'jump'
set firewall ipv4 forward filter rule 526 inbound-interface interface-group 'IG_servers'
set firewall ipv4 forward filter rule 526 jump-target 'servers-wan'
set firewall ipv4 forward filter rule 526 outbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 531 action 'jump'
set firewall ipv4 forward filter rule 531 inbound-interface interface-group 'IG_services'
set firewall ipv4 forward filter rule 531 jump-target 'services-wan'
set firewall ipv4 forward filter rule 531 outbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 536 action 'jump'
set firewall ipv4 forward filter rule 536 inbound-interface interface-group 'IG_staging'
set firewall ipv4 forward filter rule 536 jump-target 'staging-wan'
set firewall ipv4 forward filter rule 536 outbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 541 action 'jump'
set firewall ipv4 forward filter rule 541 inbound-interface interface-group 'IG_trusted'
set firewall ipv4 forward filter rule 541 jump-target 'trusted-wan'
set firewall ipv4 forward filter rule 541 outbound-interface interface-group 'IG_wan'
set firewall ipv4 forward filter rule 546 action 'drop'
set firewall ipv4 forward filter rule 546 description 'zone_wan default-action'
set firewall ipv4 forward filter rule 546 outbound-interface interface-group 'IG_wan'
set firewall ipv4 input filter default-action 'accept'
set firewall ipv4 input filter rule 1 action 'accept'
set firewall ipv4 input filter rule 1 state established 'enable'
set firewall ipv4 input filter rule 2 action 'drop'
set firewall ipv4 input filter rule 2 state invalid 'enable'
set firewall ipv4 input filter rule 3 action 'accept'
set firewall ipv4 input filter rule 3 state related 'enable'
set firewall ipv4 input filter rule 101 action 'jump'
set firewall ipv4 input filter rule 101 inbound-interface interface-group 'IG_guest'
set firewall ipv4 input filter rule 101 jump-target 'guest-local'
set firewall ipv4 input filter rule 106 action 'jump'
set firewall ipv4 input filter rule 106 inbound-interface interface-group 'IG_homelab'
set firewall ipv4 input filter rule 106 jump-target 'homelab-local'
set firewall ipv4 input filter rule 111 action 'jump'
set firewall ipv4 input filter rule 111 inbound-interface interface-group 'IG_iot'
set firewall ipv4 input filter rule 111 jump-target 'iot-local'
set firewall ipv4 input filter rule 116 action 'jump'
set firewall ipv4 input filter rule 116 inbound-interface interface-group 'IG_lan'
set firewall ipv4 input filter rule 116 jump-target 'lan-local'
set firewall ipv4 input filter rule 121 action 'jump'
set firewall ipv4 input filter rule 121 inbound-interface interface-group 'IG_servers'
set firewall ipv4 input filter rule 121 jump-target 'servers-local'
set firewall ipv4 input filter rule 126 action 'jump'
set firewall ipv4 input filter rule 126 inbound-interface interface-group 'IG_services'
set firewall ipv4 input filter rule 126 jump-target 'services-local'
set firewall ipv4 input filter rule 131 action 'jump'
set firewall ipv4 input filter rule 131 inbound-interface interface-group 'IG_staging'
set firewall ipv4 input filter rule 131 jump-target 'staging-local'
set firewall ipv4 input filter rule 136 action 'jump'
set firewall ipv4 input filter rule 136 inbound-interface interface-group 'IG_trusted'
set firewall ipv4 input filter rule 136 jump-target 'trusted-local'
set firewall ipv4 input filter rule 141 action 'jump'
set firewall ipv4 input filter rule 141 inbound-interface interface-group 'IG_wan'
set firewall ipv4 input filter rule 141 jump-target 'wan-local'
set firewall ipv4 input filter rule 146 action 'drop'
set firewall ipv4 name guest-homelab default-action 'drop'
set firewall ipv4 name guest-homelab description 'From GUEST to HOMELAB'
set firewall ipv4 name guest-homelab enable-default-log
set firewall ipv4 name guest-homelab rule 370 action 'accept'
set firewall ipv4 name guest-homelab rule 370 description 'Rule: accept plex users'
set firewall ipv4 name guest-homelab rule 370 destination group address-group 'plex-server'
set firewall ipv4 name guest-homelab rule 370 destination port '32400'
set firewall ipv4 name guest-homelab rule 370 protocol 'tcp'
set firewall ipv4 name guest-homelab rule 370 source group address-group 'plex-users'
set firewall ipv4 name guest-iot default-action 'drop'
set firewall ipv4 name guest-iot description 'From GUEST to IOT'
set firewall ipv4 name guest-iot enable-default-log
set firewall ipv4 name guest-iot rule 380 action 'accept'
set firewall ipv4 name guest-iot rule 380 description 'Rule: accept_tcp_printer_from_allowed_devices'
set firewall ipv4 name guest-iot rule 380 destination group address-group 'printers'
set firewall ipv4 name guest-iot rule 380 destination port 'http,https,9100'
set firewall ipv4 name guest-iot rule 380 protocol 'tcp'
set firewall ipv4 name guest-iot rule 430 action 'accept'
set firewall ipv4 name guest-iot rule 430 description 'Rule: accept_tcp_from_sonos_controllers_to_sonos_players'
set firewall ipv4 name guest-iot rule 430 destination group address-group 'sonos-players'
set firewall ipv4 name guest-iot rule 430 destination port '1400,1443,4444,7000,30000-65535'
set firewall ipv4 name guest-iot rule 430 protocol 'tcp'
set firewall ipv4 name guest-iot rule 430 source group address-group 'sonos-controllers'
set firewall ipv4 name guest-iot rule 431 action 'accept'
set firewall ipv4 name guest-iot rule 431 description 'Rule: accept_udp_from_sonos_controllers_to_sonos_players'
set firewall ipv4 name guest-iot rule 431 destination group address-group 'sonos-players'
set firewall ipv4 name guest-iot rule 431 destination port '319,320,30000-65535'
set firewall ipv4 name guest-iot rule 431 protocol 'udp'
set firewall ipv4 name guest-iot rule 431 source group address-group 'sonos-controllers'
set firewall ipv4 name guest-lan default-action 'drop'
set firewall ipv4 name guest-lan description 'From GUEST to LAN'
set firewall ipv4 name guest-lan enable-default-log
set firewall ipv4 name guest-local default-action 'drop'
set firewall ipv4 name guest-local description 'From GUEST to LOCAL'
set firewall ipv4 name guest-local enable-default-log
set firewall ipv4 name guest-local rule 100 action 'accept'
set firewall ipv4 name guest-local rule 100 description 'Rule: accept ntp'
set firewall ipv4 name guest-local rule 100 destination port 'ntp'
set firewall ipv4 name guest-local rule 100 protocol 'udp'
set firewall ipv4 name guest-local rule 110 action 'accept'
set firewall ipv4 name guest-local rule 110 description 'Rule: accept dhcp'
set firewall ipv4 name guest-local rule 110 destination port 'bootps,bootpc'
set firewall ipv4 name guest-local rule 110 protocol 'udp'
set firewall ipv4 name guest-local rule 110 source port 'bootps,bootpc'
set firewall ipv4 name guest-local rule 120 action 'accept'
set firewall ipv4 name guest-local rule 120 description 'Rule: accept igmp'
set firewall ipv4 name guest-local rule 120 protocol '2'
set firewall ipv4 name guest-local rule 130 action 'accept'
set firewall ipv4 name guest-local rule 130 description 'Rule: accept mdns'
set firewall ipv4 name guest-local rule 130 destination port 'mdns'
set firewall ipv4 name guest-local rule 130 protocol 'udp'
set firewall ipv4 name guest-local rule 130 source port 'mdns'
set firewall ipv4 name guest-local rule 450 action 'accept'
set firewall ipv4 name guest-local rule 450 description 'Rule: accept_discovery_from_sonos_controllers'
set firewall ipv4 name guest-local rule 450 destination port '1900,1901,1902,57621'
set firewall ipv4 name guest-local rule 450 protocol 'udp'
set firewall ipv4 name guest-local rule 450 source group address-group 'sonos-controllers'
set firewall ipv4 name guest-servers default-action 'drop'
set firewall ipv4 name guest-servers description 'From GUEST to SERVERS'
set firewall ipv4 name guest-servers enable-default-log
set firewall ipv4 name guest-services default-action 'drop'
set firewall ipv4 name guest-services description 'From GUEST to SERVICES'
set firewall ipv4 name guest-services enable-default-log
set firewall ipv4 name guest-services rule 170 action 'accept'
set firewall ipv4 name guest-services rule 170 description 'Rule: accept dns'
set firewall ipv4 name guest-services rule 170 destination port 'domain,domain-s'
set firewall ipv4 name guest-services rule 170 protocol 'tcp_udp'
set firewall ipv4 name guest-staging default-action 'drop'
set firewall ipv4 name guest-staging description 'From GUEST to STAGING'
set firewall ipv4 name guest-staging enable-default-log
set firewall ipv4 name guest-trusted default-action 'drop'
set firewall ipv4 name guest-trusted description 'From GUEST to TRUSTED'
set firewall ipv4 name guest-trusted enable-default-log
set firewall ipv4 name guest-wan default-action 'accept'
set firewall ipv4 name guest-wan description 'From IOT to WAN'
set firewall ipv4 name homelab-guest default-action 'drop'
set firewall ipv4 name homelab-guest description 'From HOMELAB to GUEST'
set firewall ipv4 name homelab-guest enable-default-log
set firewall ipv4 name homelab-homelab default-action 'accept'
set firewall ipv4 name homelab-homelab description 'From HOMELAB to HOMELAB'
set firewall ipv4 name homelab-iot default-action 'accept'
set firewall ipv4 name homelab-iot description 'From HOMELAB to IOT'
set firewall ipv4 name homelab-lan default-action 'drop'
set firewall ipv4 name homelab-lan description 'From HOMELAB to LAN'
set firewall ipv4 name homelab-lan enable-default-log
set firewall ipv4 name homelab-lan rule 140 action 'accept'
set firewall ipv4 name homelab-lan rule 140 description 'Rule: accept icmp'
set firewall ipv4 name homelab-lan rule 140 protocol 'icmp'
set firewall ipv4 name homelab-lan rule 500 action 'accept'
set firewall ipv4 name homelab-lan rule 500 description 'Rule: accept rtsp'
set firewall ipv4 name homelab-lan rule 500 destination group address-group 'unifi-unvr'
set firewall ipv4 name homelab-local default-action 'drop'
set firewall ipv4 name homelab-local description 'From HOMELAB to LOCAL'
set firewall ipv4 name homelab-local enable-default-log
set firewall ipv4 name homelab-local rule 100 action 'accept'
set firewall ipv4 name homelab-local rule 100 description 'Rule: accept ntp'
set firewall ipv4 name homelab-local rule 100 destination port 'ntp'
set firewall ipv4 name homelab-local rule 100 protocol 'udp'
set firewall ipv4 name homelab-local rule 110 action 'accept'
set firewall ipv4 name homelab-local rule 110 description 'Rule: accept dhcp'
set firewall ipv4 name homelab-local rule 110 destination port 'bootps,bootpc'
set firewall ipv4 name homelab-local rule 110 protocol 'udp'
set firewall ipv4 name homelab-local rule 110 source port 'bootps,bootpc'
set firewall ipv4 name homelab-local rule 140 action 'accept'
set firewall ipv4 name homelab-local rule 140 description 'Rule: accept icmp'
set firewall ipv4 name homelab-local rule 140 protocol 'icmp'
set firewall ipv4 name homelab-local rule 150 action 'accept'
set firewall ipv4 name homelab-local rule 150 description 'Rule: accept bgp'
set firewall ipv4 name homelab-local rule 150 destination port 'bgp'
set firewall ipv4 name homelab-local rule 150 protocol 'tcp'
set firewall ipv4 name homelab-local rule 330 action 'accept'
set firewall ipv4 name homelab-local rule 330 description 'Rule: accept iperf'
set firewall ipv4 name homelab-local rule 330 destination port '5001'
set firewall ipv4 name homelab-local rule 330 protocol 'tcp'
set firewall ipv4 name homelab-local rule 350 action 'accept'
set firewall ipv4 name homelab-local rule 350 description 'Rule: accept prometheus metrics scrape'
set firewall ipv4 name homelab-local rule 350 destination group port-group 'prometheus-metrics'
set firewall ipv4 name homelab-local rule 350 protocol 'tcp'
set firewall ipv4 name homelab-local rule 450 action 'accept'
set firewall ipv4 name homelab-local rule 450 description 'Rule: accept_discovery_from_sonos_controllers'
set firewall ipv4 name homelab-local rule 450 destination port '1900,1901,1902,57621'
set firewall ipv4 name homelab-local rule 450 protocol 'udp'
set firewall ipv4 name homelab-local rule 450 source group address-group 'sonos-controllers'
set firewall ipv4 name homelab-local rule 910 action 'drop'
set firewall ipv4 name homelab-local rule 910 description 'Rule: drop multicast to 224.0.0.1 (no log)'
set firewall ipv4 name homelab-local rule 910 destination address '224.0.0.1'
set firewall ipv4 name homelab-local rule 910 protocol '2'
set firewall ipv4 name homelab-servers default-action 'accept'
set firewall ipv4 name homelab-servers description 'From HOMELAB to SERVERS'
set firewall ipv4 name homelab-services default-action 'accept'
set firewall ipv4 name homelab-services description 'From HOMELAB to SERVICES'
set firewall ipv4 name homelab-staging default-action 'accept'
set firewall ipv4 name homelab-staging description 'From HOMELAB to STAGING'
set firewall ipv4 name homelab-trusted default-action 'drop'
set firewall ipv4 name homelab-trusted description 'From HOMELAB to TRUSTED'
set firewall ipv4 name homelab-trusted rule 140 action 'accept'
set firewall ipv4 name homelab-trusted rule 140 description 'Rule: accept icmp'
set firewall ipv4 name homelab-trusted rule 140 protocol 'icmp'
set firewall ipv4 name homelab-wan default-action 'accept'
set firewall ipv4 name homelab-wan description 'From HOMELAB to WAN'
set firewall ipv4 name iot-guest default-action 'drop'
set firewall ipv4 name iot-guest description 'From IOT to GUEST'
set firewall ipv4 name iot-guest enable-default-log
set firewall ipv4 name iot-guest rule 420 action 'accept'
set firewall ipv4 name iot-guest rule 420 description 'Rule: accept_udp_from_sonos_players_to_sonos_controllers'
set firewall ipv4 name iot-guest rule 420 destination group address-group 'sonos-controllers'
set firewall ipv4 name iot-guest rule 420 destination port '319,320,30000-65535'
set firewall ipv4 name iot-guest rule 420 protocol 'udp'
set firewall ipv4 name iot-guest rule 420 source group address-group 'sonos-players'
set firewall ipv4 name iot-guest rule 421 action 'accept'
set firewall ipv4 name iot-guest rule 421 description 'Rule: accept_tcp_from_sonos_players_to_sonos_controllers'
set firewall ipv4 name iot-guest rule 421 destination group address-group 'sonos-controllers'
set firewall ipv4 name iot-guest rule 421 destination port '1400,3400,3401,3500,30000-65535'
set firewall ipv4 name iot-guest rule 421 protocol 'tcp'
set firewall ipv4 name iot-guest rule 421 source group address-group 'sonos-players'
set firewall ipv4 name iot-homelab default-action 'drop'
set firewall ipv4 name iot-homelab description 'From IOT to HOMELAB'
set firewall ipv4 name iot-homelab enable-default-log
set firewall ipv4 name iot-homelab rule 370 action 'accept'
set firewall ipv4 name iot-homelab rule 370 description 'Rule: accept plex users'
set firewall ipv4 name iot-homelab rule 370 destination group address-group 'plex-server'
set firewall ipv4 name iot-homelab rule 370 destination port '32400'
set firewall ipv4 name iot-homelab rule 370 protocol 'tcp'
set firewall ipv4 name iot-homelab rule 370 source group address-group 'plex-users'
set firewall ipv4 name iot-homelab rule 420 action 'accept'
set firewall ipv4 name iot-homelab rule 420 description 'Rule: accept_udp_from_sonos_players_to_sonos_controllers'
set firewall ipv4 name iot-homelab rule 420 destination group address-group 'sonos-controllers'
set firewall ipv4 name iot-homelab rule 420 destination port '319,320,30000-65535'
set firewall ipv4 name iot-homelab rule 420 protocol 'udp'
set firewall ipv4 name iot-homelab rule 420 source group address-group 'sonos-players'
set firewall ipv4 name iot-homelab rule 421 action 'accept'
set firewall ipv4 name iot-homelab rule 421 description 'Rule: accept_tcp_from_sonos_players_to_sonos_controllers'
set firewall ipv4 name iot-homelab rule 421 destination group address-group 'sonos-controllers'
set firewall ipv4 name iot-homelab rule 421 destination port '1400,3400,3401,3500,30000-65535'
set firewall ipv4 name iot-homelab rule 421 protocol 'tcp'
set firewall ipv4 name iot-homelab rule 421 source group address-group 'sonos-players'
set firewall ipv4 name iot-homelab rule 460 action 'accept'
set firewall ipv4 name iot-homelab rule 460 description 'Rule: accept_music_library_sonos_players'
set firewall ipv4 name iot-homelab rule 460 destination group address-group 'sonos-library'
set firewall ipv4 name iot-homelab rule 460 destination port '4534,http,https'
set firewall ipv4 name iot-homelab rule 460 protocol 'tcp'
set firewall ipv4 name iot-homelab rule 460 source group address-group 'sonos-players'
set firewall ipv4 name iot-lan default-action 'drop'
set firewall ipv4 name iot-lan description 'From IOT to LAN'
set firewall ipv4 name iot-lan enable-default-log
set firewall ipv4 name iot-local default-action 'drop'
set firewall ipv4 name iot-local description 'From IOT to LOCAL'
set firewall ipv4 name iot-local enable-default-log
set firewall ipv4 name iot-local rule 100 action 'accept'
set firewall ipv4 name iot-local rule 100 description 'Rule: accept ntp'
set firewall ipv4 name iot-local rule 100 destination port 'ntp'
set firewall ipv4 name iot-local rule 100 protocol 'udp'
set firewall ipv4 name iot-local rule 110 action 'accept'
set firewall ipv4 name iot-local rule 110 description 'Rule: accept dhcp'
set firewall ipv4 name iot-local rule 110 destination port 'bootps,bootpc'
set firewall ipv4 name iot-local rule 110 protocol 'udp'
set firewall ipv4 name iot-local rule 110 source port 'bootps,bootpc'
set firewall ipv4 name iot-local rule 120 action 'accept'
set firewall ipv4 name iot-local rule 120 description 'Rule: accept igmp'
set firewall ipv4 name iot-local rule 120 protocol '2'
set firewall ipv4 name iot-local rule 130 action 'accept'
set firewall ipv4 name iot-local rule 130 description 'Rule: accept mdns'
set firewall ipv4 name iot-local rule 130 destination port 'mdns'
set firewall ipv4 name iot-local rule 130 protocol 'udp'
set firewall ipv4 name iot-local rule 130 source port 'mdns'
set firewall ipv4 name iot-local rule 440 action 'accept'
set firewall ipv4 name iot-local rule 440 description 'Rule: accept_discovery_from_sonos_players'
set firewall ipv4 name iot-local rule 440 destination port '1900,1901,1902'
set firewall ipv4 name iot-local rule 440 protocol 'udp'
set firewall ipv4 name iot-local rule 440 source group address-group 'sonos-players'
set firewall ipv4 name iot-servers default-action 'drop'
set firewall ipv4 name iot-servers description 'From IOT to SERVERS'
set firewall ipv4 name iot-servers enable-default-log
set firewall ipv4 name iot-services default-action 'drop'
set firewall ipv4 name iot-services description 'From IOT to SERVICES'
set firewall ipv4 name iot-services enable-default-log
set firewall ipv4 name iot-staging default-action 'drop'
set firewall ipv4 name iot-staging description 'From IOT to STAGING'
set firewall ipv4 name iot-staging enable-default-log
set firewall ipv4 name iot-trusted default-action 'drop'
set firewall ipv4 name iot-trusted description 'From IOT to TRUSTED'
set firewall ipv4 name iot-trusted enable-default-log
set firewall ipv4 name iot-trusted rule 360 action 'accept'
set firewall ipv4 name iot-trusted rule 360 description 'Rule: accept scanner traffic'
set firewall ipv4 name iot-trusted rule 360 destination group address-group 'scanner-clients'
set firewall ipv4 name iot-trusted rule 360 destination group port-group 'scanner-outbound-ports'
set firewall ipv4 name iot-trusted rule 360 protocol 'udp'
set firewall ipv4 name iot-trusted rule 420 action 'accept'
set firewall ipv4 name iot-trusted rule 420 description 'Rule: accept_udp_from_sonos_players_to_sonos_controllers'
set firewall ipv4 name iot-trusted rule 420 destination group address-group 'sonos-controllers'
set firewall ipv4 name iot-trusted rule 420 destination port '319,320,30000-65535'
set firewall ipv4 name iot-trusted rule 420 protocol 'udp'
set firewall ipv4 name iot-trusted rule 420 source group address-group 'sonos-players'
set firewall ipv4 name iot-trusted rule 421 action 'accept'
set firewall ipv4 name iot-trusted rule 421 description 'Rule: accept_tcp_from_sonos_players_to_sonos_controllers'
set firewall ipv4 name iot-trusted rule 421 destination group address-group 'sonos-controllers'
set firewall ipv4 name iot-trusted rule 421 destination port '1400,3400,3401,3500,30000-65535'
set firewall ipv4 name iot-trusted rule 421 protocol 'tcp'
set firewall ipv4 name iot-trusted rule 421 source group address-group 'sonos-players'
set firewall ipv4 name iot-wan default-action 'accept'
set firewall ipv4 name iot-wan description 'From IOT to WAN'
set firewall ipv4 name lan-guest default-action 'drop'
set firewall ipv4 name lan-guest description 'From LAN to GUEST'
set firewall ipv4 name lan-guest enable-default-log
set firewall ipv4 name lan-homelab default-action 'drop'
set firewall ipv4 name lan-homelab description 'From LAN to HOMELAB'
set firewall ipv4 name lan-homelab enable-default-log
set firewall ipv4 name lan-iot default-action 'drop'
set firewall ipv4 name lan-iot description 'From LAN to IOT'
set firewall ipv4 name lan-iot enable-default-log
set firewall ipv4 name lan-local default-action 'drop'
set firewall ipv4 name lan-local description 'From LAN to LOCAL'
set firewall ipv4 name lan-local enable-default-log
set firewall ipv4 name lan-local rule 100 action 'accept'
set firewall ipv4 name lan-local rule 100 description 'Rule: accept ntp'
set firewall ipv4 name lan-local rule 100 destination port 'ntp'
set firewall ipv4 name lan-local rule 100 protocol 'udp'
set firewall ipv4 name lan-local rule 110 action 'accept'
set firewall ipv4 name lan-local rule 110 description 'Rule: accept dhcp'
set firewall ipv4 name lan-local rule 110 destination port 'bootps,bootpc'
set firewall ipv4 name lan-local rule 110 protocol 'udp'
set firewall ipv4 name lan-local rule 110 source port 'bootps,bootpc'
set firewall ipv4 name lan-local rule 160 action 'accept'
set firewall ipv4 name lan-local rule 160 description 'Rule: accept ssh'
set firewall ipv4 name lan-local rule 160 destination port 'ssh'
set firewall ipv4 name lan-local rule 160 protocol 'tcp'
set firewall ipv4 name lan-local rule 900 action 'drop'
set firewall ipv4 name lan-local rule 900 description 'Rule: drop 10001 (no log)'
set firewall ipv4 name lan-local rule 900 destination port '10001'
set firewall ipv4 name lan-local rule 900 protocol 'udp'
set firewall ipv4 name lan-local rule 910 action 'drop'
set firewall ipv4 name lan-local rule 910 description 'Rule: drop multicast to 224.0.0.1 (no log)'
set firewall ipv4 name lan-local rule 910 destination address '224.0.0.1'
set firewall ipv4 name lan-local rule 910 protocol '2'
set firewall ipv4 name lan-servers default-action 'drop'
set firewall ipv4 name lan-servers description 'From LAN to SERVERS'
set firewall ipv4 name lan-servers enable-default-log
set firewall ipv4 name lan-services default-action 'accept'
set firewall ipv4 name lan-services description 'From LAN to SERVICES'
set firewall ipv4 name lan-services enable-default-log
set firewall ipv4 name lan-services rule 170 action 'accept'
set firewall ipv4 name lan-services rule 170 description 'Rule: accept dns'
set firewall ipv4 name lan-services rule 170 destination port 'domain,domain-s'
set firewall ipv4 name lan-services rule 170 protocol 'tcp_udp'
set firewall ipv4 name lan-services rule 300 action 'accept'
set firewall ipv4 name lan-services rule 300 description 'Rule: accept unifi'
set firewall ipv4 name lan-services rule 300 destination group address-group 'unifi-controller'
set firewall ipv4 name lan-staging default-action 'drop'
set firewall ipv4 name lan-staging description 'From LAN to STAGING'
set firewall ipv4 name lan-staging enable-default-log
set firewall ipv4 name lan-trusted default-action 'drop'
set firewall ipv4 name lan-trusted description 'From LAN to TRUSTED'
set firewall ipv4 name lan-trusted enable-default-log
set firewall ipv4 name lan-trusted rule 900 action 'drop'
set firewall ipv4 name lan-trusted rule 900 description 'Rule: drop 10001 (no log)'
set firewall ipv4 name lan-trusted rule 900 destination port '10001'
set firewall ipv4 name lan-trusted rule 900 protocol 'udp'
set firewall ipv4 name lan-wan default-action 'accept'
set firewall ipv4 name lan-wan description 'From LAN to WAN'
set firewall ipv4 name local-guest default-action 'drop'
set firewall ipv4 name local-guest description 'From LOCAL to GUEST'
set firewall ipv4 name local-guest enable-default-log
set firewall ipv4 name local-guest rule 120 action 'accept'
set firewall ipv4 name local-guest rule 120 description 'Rule: accept igmp'
set firewall ipv4 name local-guest rule 120 protocol '2'
set firewall ipv4 name local-guest rule 130 action 'accept'
set firewall ipv4 name local-guest rule 130 description 'Rule: accept mdns'
set firewall ipv4 name local-guest rule 130 destination port 'mdns'
set firewall ipv4 name local-guest rule 130 protocol 'udp'
set firewall ipv4 name local-guest rule 130 source port 'mdns'
set firewall ipv4 name local-guest rule 410 action 'accept'
set firewall ipv4 name local-guest rule 410 description 'Rule: accept_discovery_from_sonos_players'
set firewall ipv4 name local-guest rule 410 destination port '1900,1901,1902'
set firewall ipv4 name local-guest rule 410 protocol 'udp'
set firewall ipv4 name local-guest rule 410 source group address-group 'sonos-players'
set firewall ipv4 name local-homelab default-action 'drop'
set firewall ipv4 name local-homelab description 'From LOCAL to HOMELAB'
set firewall ipv4 name local-homelab enable-default-log
set firewall ipv4 name local-homelab rule 140 action 'accept'
set firewall ipv4 name local-homelab rule 140 description 'Rule: accept icmp'
set firewall ipv4 name local-homelab rule 140 protocol 'icmp'
set firewall ipv4 name local-homelab rule 150 action 'accept'
set firewall ipv4 name local-homelab rule 150 description 'Rule: accept bgp'
set firewall ipv4 name local-homelab rule 150 destination port 'bgp'
set firewall ipv4 name local-homelab rule 150 protocol 'tcp'
set firewall ipv4 name local-homelab rule 310 action 'accept'
set firewall ipv4 name local-homelab rule 310 description 'Rule: accept vector syslog'
set firewall ipv4 name local-homelab rule 310 destination port '6003'
set firewall ipv4 name local-homelab rule 310 protocol 'tcp'
set firewall ipv4 name local-homelab rule 410 action 'accept'
set firewall ipv4 name local-homelab rule 410 description 'Rule: accept_discovery_from_sonos_players'
set firewall ipv4 name local-homelab rule 410 destination port '1900,1901,1902'
set firewall ipv4 name local-homelab rule 410 protocol 'udp'
set firewall ipv4 name local-homelab rule 410 source group address-group 'sonos-players'
set firewall ipv4 name local-iot default-action 'drop'
set firewall ipv4 name local-iot description 'From LOCAL to IOT'
set firewall ipv4 name local-iot enable-default-log
set firewall ipv4 name local-iot rule 120 action 'accept'
set firewall ipv4 name local-iot rule 120 description 'Rule: accept igmp'
set firewall ipv4 name local-iot rule 120 protocol '2'
set firewall ipv4 name local-iot rule 130 action 'accept'
set firewall ipv4 name local-iot rule 130 description 'Rule: accept mdns'
set firewall ipv4 name local-iot rule 130 destination port 'mdns'
set firewall ipv4 name local-iot rule 130 protocol 'udp'
set firewall ipv4 name local-iot rule 130 source port 'mdns'
set firewall ipv4 name local-iot rule 140 action 'accept'
set firewall ipv4 name local-iot rule 140 description 'Rule: accept icmp'
set firewall ipv4 name local-iot rule 140 protocol 'icmp'
set firewall ipv4 name local-iot rule 400 action 'accept'
set firewall ipv4 name local-iot rule 400 description 'Rule: accept_discovery_from_sonos_controllers'
set firewall ipv4 name local-iot rule 400 destination port '1900,1901,1902,57621'
set firewall ipv4 name local-iot rule 400 protocol 'udp'
set firewall ipv4 name local-iot rule 400 source group address-group 'sonos-controllers'
set firewall ipv4 name local-lan default-action 'drop'
set firewall ipv4 name local-lan description 'From LOCAL to LAN'
set firewall ipv4 name local-lan enable-default-log
set firewall ipv4 name local-lan rule 140 action 'accept'
set firewall ipv4 name local-lan rule 140 description 'Rule: accept icmp'
set firewall ipv4 name local-lan rule 140 protocol 'icmp'
set firewall ipv4 name local-lan rule 160 action 'accept'
set firewall ipv4 name local-lan rule 160 description 'Rule: accept ssh'
set firewall ipv4 name local-lan rule 160 destination port 'ssh'
set firewall ipv4 name local-lan rule 160 protocol 'tcp'
set firewall ipv4 name local-servers default-action 'drop'
set firewall ipv4 name local-servers description 'From LOCAL to SERVERS'
set firewall ipv4 name local-servers enable-default-log
set firewall ipv4 name local-servers rule 140 action 'accept'
set firewall ipv4 name local-servers rule 140 description 'Rule: accept icmp'
set firewall ipv4 name local-servers rule 140 protocol 'icmp'
set firewall ipv4 name local-servers rule 150 action 'accept'
set firewall ipv4 name local-servers rule 150 description 'Rule: accept bgp'
set firewall ipv4 name local-servers rule 150 destination port 'bgp'
set firewall ipv4 name local-servers rule 150 protocol 'tcp'
set firewall ipv4 name local-services default-action 'accept'
set firewall ipv4 name local-services description 'From LOCAL to SERVICES'
set firewall ipv4 name local-staging default-action 'drop'
set firewall ipv4 name local-staging description 'From LOCAL to STAGING'
set firewall ipv4 name local-staging enable-default-log
set firewall ipv4 name local-staging rule 140 action 'accept'
set firewall ipv4 name local-staging rule 140 description 'Rule: accept icmp'
set firewall ipv4 name local-staging rule 140 protocol 'icmp'
set firewall ipv4 name local-staging rule 150 action 'accept'
set firewall ipv4 name local-staging rule 150 description 'Rule: accept bgp'
set firewall ipv4 name local-staging rule 150 destination port 'bgp'
set firewall ipv4 name local-staging rule 150 protocol 'tcp'
set firewall ipv4 name local-trusted default-action 'drop'
set firewall ipv4 name local-trusted description 'From LOCAL to TRUSTED'
set firewall ipv4 name local-trusted enable-default-log
set firewall ipv4 name local-trusted rule 120 action 'accept'
set firewall ipv4 name local-trusted rule 120 description 'Rule: accept igmp'
set firewall ipv4 name local-trusted rule 120 protocol '2'
set firewall ipv4 name local-trusted rule 130 action 'accept'
set firewall ipv4 name local-trusted rule 130 description 'Rule: accept mdns'
set firewall ipv4 name local-trusted rule 130 destination port 'mdns'
set firewall ipv4 name local-trusted rule 130 protocol 'udp'
set firewall ipv4 name local-trusted rule 130 source port 'mdns'
set firewall ipv4 name local-trusted rule 140 action 'accept'
set firewall ipv4 name local-trusted rule 140 description 'Rule: accept icmp'
set firewall ipv4 name local-trusted rule 140 protocol 'icmp'
set firewall ipv4 name local-trusted rule 180 action 'accept'
set firewall ipv4 name local-trusted rule 180 description 'Rule: accept wireguard'
set firewall ipv4 name local-trusted rule 180 destination port '51820'
set firewall ipv4 name local-trusted rule 180 protocol 'udp'
set firewall ipv4 name local-trusted rule 410 action 'accept'
set firewall ipv4 name local-trusted rule 410 description 'Rule: accept_discovery_from_sonos_players'
set firewall ipv4 name local-trusted rule 410 destination port '1900,1901,1902'
set firewall ipv4 name local-trusted rule 410 protocol 'udp'
set firewall ipv4 name local-trusted rule 410 source group address-group 'sonos-players'
set firewall ipv4 name local-wan default-action 'accept'
set firewall ipv4 name local-wan description 'From LOCAL to WAN'
set firewall ipv4 name servers-guest default-action 'drop'
set firewall ipv4 name servers-guest description 'From SERVERS to GUEST'
set firewall ipv4 name servers-guest enable-default-log
set firewall ipv4 name servers-homelab default-action 'accept'
set firewall ipv4 name servers-homelab description 'From SERVERS to HOMELAB'
set firewall ipv4 name servers-iot default-action 'accept'
set firewall ipv4 name servers-iot description 'From SERVERS to IOT'
set firewall ipv4 name servers-lan default-action 'drop'
set firewall ipv4 name servers-lan description 'From SERVERS to LAN'
set firewall ipv4 name servers-lan enable-default-log
set firewall ipv4 name servers-lan rule 140 action 'accept'
set firewall ipv4 name servers-lan rule 140 description 'Rule: accept icmp'
set firewall ipv4 name servers-lan rule 140 protocol 'icmp'
set firewall ipv4 name servers-lan rule 500 action 'accept'
set firewall ipv4 name servers-lan rule 500 description 'Rule: accept rtsp'
set firewall ipv4 name servers-lan rule 500 destination group address-group 'unifi-unvr'
set firewall ipv4 name servers-local default-action 'drop'
set firewall ipv4 name servers-local description 'From SERVERS to LOCAL'
set firewall ipv4 name servers-local enable-default-log
set firewall ipv4 name servers-local rule 100 action 'accept'
set firewall ipv4 name servers-local rule 100 description 'Rule: accept ntp'
set firewall ipv4 name servers-local rule 100 destination port 'ntp'
set firewall ipv4 name servers-local rule 100 protocol 'udp'
set firewall ipv4 name servers-local rule 110 action 'accept'
set firewall ipv4 name servers-local rule 110 description 'Rule: accept dhcp'
set firewall ipv4 name servers-local rule 110 destination port 'bootps,bootpc'
set firewall ipv4 name servers-local rule 110 protocol 'udp'
set firewall ipv4 name servers-local rule 110 source port 'bootps,bootpc'
set firewall ipv4 name servers-local rule 140 action 'accept'
set firewall ipv4 name servers-local rule 140 description 'Rule: accept icmp'
set firewall ipv4 name servers-local rule 140 protocol 'icmp'
set firewall ipv4 name servers-local rule 150 action 'accept'
set firewall ipv4 name servers-local rule 150 description 'Rule: accept bgp'
set firewall ipv4 name servers-local rule 150 destination port 'bgp'
set firewall ipv4 name servers-local rule 150 protocol 'tcp'
set firewall ipv4 name servers-local rule 160 action 'accept'
set firewall ipv4 name servers-local rule 160 description 'Rule: accept ssh'
set firewall ipv4 name servers-local rule 160 destination port 'ssh'
set firewall ipv4 name servers-local rule 160 protocol 'tcp'
set firewall ipv4 name servers-local rule 330 action 'accept'
set firewall ipv4 name servers-local rule 330 description 'Rule: accept iperf'
set firewall ipv4 name servers-local rule 330 destination port '5001'
set firewall ipv4 name servers-local rule 330 protocol 'tcp'
set firewall ipv4 name servers-local rule 910 action 'drop'
set firewall ipv4 name servers-local rule 910 description 'Rule: drop multicast to 224.0.0.1 (no log)'
set firewall ipv4 name servers-local rule 910 destination address '224.0.0.1'
set firewall ipv4 name servers-local rule 910 protocol '2'
set firewall ipv4 name servers-services default-action 'accept'
set firewall ipv4 name servers-services description 'From SERVERS to SERVICES'
set firewall ipv4 name servers-staging default-action 'accept'
set firewall ipv4 name servers-staging description 'From SERVERS to STAGING'
set firewall ipv4 name servers-trusted default-action 'drop'
set firewall ipv4 name servers-trusted description 'From SERVERS to TRUSTED'
set firewall ipv4 name servers-trusted rule 140 action 'accept'
set firewall ipv4 name servers-trusted rule 140 description 'Rule: accept icmp'
set firewall ipv4 name servers-trusted rule 140 protocol 'icmp'
set firewall ipv4 name servers-trusted rule 160 action 'accept'
set firewall ipv4 name servers-trusted rule 160 description 'Rule: accept ssh'
set firewall ipv4 name servers-trusted rule 160 destination port 'ssh'
set firewall ipv4 name servers-trusted rule 160 protocol 'tcp'
set firewall ipv4 name servers-wan default-action 'accept'
set firewall ipv4 name servers-wan description 'From SERVERS to WAN'
set firewall ipv4 name services-guest default-action 'drop'
set firewall ipv4 name services-guest description 'From SERVICES to GUEST'
set firewall ipv4 name services-guest enable-default-log
set firewall ipv4 name services-homelab default-action 'accept'
set firewall ipv4 name services-homelab description 'From SERVICES to HOMELAB'
set firewall ipv4 name services-iot default-action 'drop'
set firewall ipv4 name services-iot description 'From SERVICES to IOT'
set firewall ipv4 name services-iot enable-default-log
set firewall ipv4 name services-iot rule 140 action 'accept'
set firewall ipv4 name services-iot rule 140 description 'Rule: accept icmp'
set firewall ipv4 name services-iot rule 140 protocol 'icmp'
set firewall ipv4 name services-lan default-action 'accept'
set firewall ipv4 name services-lan description 'From SERVICES to LAN'
set firewall ipv4 name services-lan enable-default-log
set firewall ipv4 name services-lan rule 140 action 'accept'
set firewall ipv4 name services-lan rule 140 description 'Rule: accept icmp'
set firewall ipv4 name services-lan rule 140 protocol 'icmp'
set firewall ipv4 name services-local default-action 'drop'
set firewall ipv4 name services-local description 'From SERVICES to LOCAL'
set firewall ipv4 name services-local enable-default-log
set firewall ipv4 name services-local rule 100 action 'accept'
set firewall ipv4 name services-local rule 100 description 'Rule: accept ntp'
set firewall ipv4 name services-local rule 100 destination port 'ntp'
set firewall ipv4 name services-local rule 100 protocol 'udp'
set firewall ipv4 name services-local rule 110 action 'accept'
set firewall ipv4 name services-local rule 110 description 'Rule: accept dhcp'
set firewall ipv4 name services-local rule 110 destination port 'bootps,bootpc'
set firewall ipv4 name services-local rule 110 protocol 'udp'
set firewall ipv4 name services-local rule 110 source port 'bootps,bootpc'
set firewall ipv4 name services-servers default-action 'accept'
set firewall ipv4 name services-servers description 'From SERVICES to SERVERS'
set firewall ipv4 name services-staging default-action 'accept'
set firewall ipv4 name services-staging description 'From SERVICES to STAGING'
set firewall ipv4 name services-trusted default-action 'drop'
set firewall ipv4 name services-trusted description 'From SERVICES to TRUSTED'
set firewall ipv4 name services-trusted enable-default-log
set firewall ipv4 name services-wan default-action 'accept'
set firewall ipv4 name services-wan description 'From SERVICES to WAN'
set firewall ipv4 name staging-guest default-action 'drop'
set firewall ipv4 name staging-guest description 'From STAGING to GUEST'
set firewall ipv4 name staging-guest enable-default-log
set firewall ipv4 name staging-homelab default-action 'accept'
set firewall ipv4 name staging-homelab description 'From STAGING to HOMELAB'
set firewall ipv4 name staging-iot default-action 'accept'
set firewall ipv4 name staging-iot description 'From STAGING to IOT'
set firewall ipv4 name staging-lan default-action 'drop'
set firewall ipv4 name staging-lan description 'From STAGING to LAN'
set firewall ipv4 name staging-lan enable-default-log
set firewall ipv4 name staging-lan rule 140 action 'accept'
set firewall ipv4 name staging-lan rule 140 description 'Rule: accept icmp'
set firewall ipv4 name staging-lan rule 140 protocol 'icmp'
set firewall ipv4 name staging-local default-action 'drop'
set firewall ipv4 name staging-local description 'From STAGING to LOCAL'
set firewall ipv4 name staging-local enable-default-log
set firewall ipv4 name staging-local rule 100 action 'accept'
set firewall ipv4 name staging-local rule 100 description 'Rule: accept ntp'
set firewall ipv4 name staging-local rule 100 destination port 'ntp'
set firewall ipv4 name staging-local rule 100 protocol 'udp'
set firewall ipv4 name staging-local rule 110 action 'accept'
set firewall ipv4 name staging-local rule 110 description 'Rule: accept dhcp'
set firewall ipv4 name staging-local rule 110 destination port 'bootps,bootpc'
set firewall ipv4 name staging-local rule 110 protocol 'udp'
set firewall ipv4 name staging-local rule 110 source port 'bootps,bootpc'
set firewall ipv4 name staging-local rule 140 action 'accept'
set firewall ipv4 name staging-local rule 140 description 'Rule: accept icmp'
set firewall ipv4 name staging-local rule 140 protocol 'icmp'
set firewall ipv4 name staging-local rule 150 action 'accept'
set firewall ipv4 name staging-local rule 150 description 'Rule: accept bgp'
set firewall ipv4 name staging-local rule 150 destination port 'bgp'
set firewall ipv4 name staging-local rule 150 protocol 'tcp'
set firewall ipv4 name staging-local rule 350 action 'accept'
set firewall ipv4 name staging-local rule 350 description 'Rule: accept prometheus metrics scrape'
set firewall ipv4 name staging-local rule 350 destination group port-group 'prometheus-metrics'
set firewall ipv4 name staging-local rule 350 protocol 'tcp'
set firewall ipv4 name staging-local rule 910 action 'drop'
set firewall ipv4 name staging-local rule 910 description 'Rule: drop multicast to 224.0.0.1 (no log)'
set firewall ipv4 name staging-local rule 910 destination address '224.0.0.1'
set firewall ipv4 name staging-local rule 910 protocol '2'
set firewall ipv4 name staging-servers default-action 'accept'
set firewall ipv4 name staging-servers description 'From STAGING to SERVERS'
set firewall ipv4 name staging-services default-action 'accept'
set firewall ipv4 name staging-services description 'From STAGING to SERVICES'
set firewall ipv4 name staging-trusted default-action 'drop'
set firewall ipv4 name staging-trusted description 'From STAGING to TRUSTED'
set firewall ipv4 name staging-trusted rule 140 action 'accept'
set firewall ipv4 name staging-trusted rule 140 description 'Rule: accept icmp'
set firewall ipv4 name staging-trusted rule 140 protocol 'icmp'
set firewall ipv4 name staging-wan default-action 'accept'
set firewall ipv4 name staging-wan description 'From STAGING to WAN'
set firewall ipv4 name trusted-guest default-action 'drop'
set firewall ipv4 name trusted-guest description 'From TRUSTED to GUEST'
set firewall ipv4 name trusted-guest enable-default-log
set firewall ipv4 name trusted-homelab default-action 'drop'
set firewall ipv4 name trusted-homelab description 'From TRUSTED to HOMELAB'
set firewall ipv4 name trusted-homelab enable-default-log
set firewall ipv4 name trusted-homelab rule 520 action 'accept'
set firewall ipv4 name trusted-homelab rule 520 description 'Rule: accept scotte'
set firewall ipv4 name trusted-homelab rule 520 source group address-group 'scotte-devices'
set firewall ipv4 name trusted-homelab rule 530 action 'accept'
set firewall ipv4 name trusted-homelab rule 530 description 'Rule: accept sophie'
set firewall ipv4 name trusted-homelab rule 530 source group address-group 'sophie-devices'
set firewall ipv4 name trusted-iot default-action 'accept'
set firewall ipv4 name trusted-iot description 'From TRUSTED to IOT'
set firewall ipv4 name trusted-iot rule 430 action 'accept'
set firewall ipv4 name trusted-iot rule 430 description 'Rule: accept_tcp_from_sonos_controllers_to_sonos_players'
set firewall ipv4 name trusted-iot rule 430 destination group address-group 'sonos-players'
set firewall ipv4 name trusted-iot rule 430 destination port '1400,1443,4444,7000,30000-65535'
set firewall ipv4 name trusted-iot rule 430 protocol 'tcp'
set firewall ipv4 name trusted-iot rule 430 source group address-group 'sonos-controllers'
set firewall ipv4 name trusted-iot rule 431 action 'accept'
set firewall ipv4 name trusted-iot rule 431 description 'Rule: accept_udp_from_sonos_controllers_to_sonos_players'
set firewall ipv4 name trusted-iot rule 431 destination group address-group 'sonos-players'
set firewall ipv4 name trusted-iot rule 431 destination port '319,320,30000-65535'
set firewall ipv4 name trusted-iot rule 431 protocol 'udp'
set firewall ipv4 name trusted-iot rule 431 source group address-group 'sonos-controllers'
set firewall ipv4 name trusted-lan default-action 'drop'
set firewall ipv4 name trusted-lan description 'From TRUSTED to LAN'
set firewall ipv4 name trusted-lan enable-default-log
set firewall ipv4 name trusted-lan rule 520 action 'accept'
set firewall ipv4 name trusted-lan rule 520 description 'Rule: accept scotte'
set firewall ipv4 name trusted-lan rule 520 source group address-group 'scotte-devices'
set firewall ipv4 name trusted-lan rule 540 action 'accept'
set firewall ipv4 name trusted-lan rule 540 description 'Rule: accept cameras'
set firewall ipv4 name trusted-lan rule 540 source group address-group 'unifi-cameras'
set firewall ipv4 name trusted-local default-action 'drop'
set firewall ipv4 name trusted-local description 'From TRUSTED to LOCAL'
set firewall ipv4 name trusted-local enable-default-log
set firewall ipv4 name trusted-local rule 100 action 'accept'
set firewall ipv4 name trusted-local rule 100 description 'Rule: accept ntp'
set firewall ipv4 name trusted-local rule 100 destination port 'ntp'
set firewall ipv4 name trusted-local rule 100 protocol 'udp'
set firewall ipv4 name trusted-local rule 110 action 'accept'
set firewall ipv4 name trusted-local rule 110 description 'Rule: accept dhcp'
set firewall ipv4 name trusted-local rule 110 destination port 'bootps,bootpc'
set firewall ipv4 name trusted-local rule 110 protocol 'udp'
set firewall ipv4 name trusted-local rule 110 source port 'bootps,bootpc'
set firewall ipv4 name trusted-local rule 120 action 'accept'
set firewall ipv4 name trusted-local rule 120 description 'Rule: accept igmp'
set firewall ipv4 name trusted-local rule 120 protocol '2'
set firewall ipv4 name trusted-local rule 130 action 'accept'
set firewall ipv4 name trusted-local rule 130 description 'Rule: accept mdns'
set firewall ipv4 name trusted-local rule 130 destination port 'mdns'
set firewall ipv4 name trusted-local rule 130 protocol 'udp'
set firewall ipv4 name trusted-local rule 130 source port 'mdns'
set firewall ipv4 name trusted-local rule 140 action 'accept'
set firewall ipv4 name trusted-local rule 140 description 'Rule: accept icmp'
set firewall ipv4 name trusted-local rule 140 protocol 'icmp'
set firewall ipv4 name trusted-local rule 160 action 'accept'
set firewall ipv4 name trusted-local rule 160 description 'Rule: accept ssh'
set firewall ipv4 name trusted-local rule 160 destination port 'ssh'
set firewall ipv4 name trusted-local rule 160 protocol 'tcp'
set firewall ipv4 name trusted-local rule 320 action 'accept'
set firewall ipv4 name trusted-local rule 320 description 'Rule: accept vnstat'
set firewall ipv4 name trusted-local rule 320 destination port '8685'
set firewall ipv4 name trusted-local rule 320 protocol 'tcp'
set firewall ipv4 name trusted-local rule 330 action 'accept'
set firewall ipv4 name trusted-local rule 330 description 'Rule: accept iperf'
set firewall ipv4 name trusted-local rule 330 destination port '5001'
set firewall ipv4 name trusted-local rule 330 protocol 'tcp'
set firewall ipv4 name trusted-local rule 340 action 'drop'
set firewall ipv4 name trusted-local rule 340 description 'Rule: ignore scansnap probe'
set firewall ipv4 name trusted-local rule 340 destination address '255.255.255.255'
set firewall ipv4 name trusted-local rule 340 destination port '52217'
set firewall ipv4 name trusted-local rule 340 protocol 'udp'
set firewall ipv4 name trusted-local rule 340 source group address-group 'scanner-clients'
set firewall ipv4 name trusted-local rule 450 action 'accept'
set firewall ipv4 name trusted-local rule 450 description 'Rule: accept_discovery_from_sonos_controllers'
set firewall ipv4 name trusted-local rule 450 destination port '1900,1901,1902,57621'
set firewall ipv4 name trusted-local rule 450 protocol 'udp'
set firewall ipv4 name trusted-local rule 450 source group address-group 'sonos-controllers'
set firewall ipv4 name trusted-servers default-action 'drop'
set firewall ipv4 name trusted-servers description 'From TRUSTED to SERVERS'
set firewall ipv4 name trusted-servers enable-default-log
set firewall ipv4 name trusted-servers rule 520 action 'accept'
set firewall ipv4 name trusted-servers rule 520 description 'Rule: accept scotte'
set firewall ipv4 name trusted-servers rule 520 source group address-group 'scotte-devices'
set firewall ipv4 name trusted-servers rule 530 action 'accept'
set firewall ipv4 name trusted-servers rule 530 description 'Rule: accept sophie'
set firewall ipv4 name trusted-servers rule 530 source group address-group 'sophie-devices'
set firewall ipv4 name trusted-services default-action 'accept'
set firewall ipv4 name trusted-services description 'From TRUSTED to SERVICES'
set firewall ipv4 name trusted-staging default-action 'drop'
set firewall ipv4 name trusted-staging description 'From TRUSTED to STAGING'
set firewall ipv4 name trusted-staging enable-default-log
set firewall ipv4 name trusted-staging rule 520 action 'accept'
set firewall ipv4 name trusted-staging rule 520 description 'Rule: accept scotte'
set firewall ipv4 name trusted-staging rule 520 source group address-group 'scotte-devices'
set firewall ipv4 name trusted-wan default-action 'accept'
set firewall ipv4 name trusted-wan description 'From TRUSTED to WAN'
set firewall ipv4 name wan-guest default-action 'drop'
set firewall ipv4 name wan-guest description 'From WAN to GUEST'
set firewall ipv4 name wan-guest enable-default-log
set firewall ipv4 name wan-homelab default-action 'drop'
set firewall ipv4 name wan-homelab description 'From WAN to HOMELAB'
set firewall ipv4 name wan-homelab enable-default-log
set firewall ipv4 name wan-iot default-action 'drop'
set firewall ipv4 name wan-iot description 'From WAN to IOT'
set firewall ipv4 name wan-iot enable-default-log
set firewall ipv4 name wan-lan default-action 'drop'
set firewall ipv4 name wan-lan description 'From WAN to LAN'
set firewall ipv4 name wan-lan enable-default-log
set firewall ipv4 name wan-local default-action 'drop'
set firewall ipv4 name wan-local description 'From WAN to LOCAL'
set firewall ipv4 name wan-local enable-default-log
set firewall ipv4 name wan-local rule 180 action 'accept'
set firewall ipv4 name wan-local rule 180 description 'Rule: accept wireguard'
set firewall ipv4 name wan-local rule 180 destination port '51820'
set firewall ipv4 name wan-local rule 180 protocol 'udp'
set firewall ipv4 name wan-servers default-action 'drop'
set firewall ipv4 name wan-servers description 'From WAN to SERVERS'
set firewall ipv4 name wan-servers enable-default-log
set firewall ipv4 name wan-services default-action 'drop'
set firewall ipv4 name wan-services description 'From WAN to SERVICES'
set firewall ipv4 name wan-services enable-default-log
set firewall ipv4 name wan-staging default-action 'drop'
set firewall ipv4 name wan-staging description 'From WAN to STAGING'
set firewall ipv4 name wan-staging enable-default-log
set firewall ipv4 name wan-trusted default-action 'drop'
set firewall ipv4 name wan-trusted description 'From WAN to TRUSTED'
set firewall ipv4 name wan-trusted enable-default-log
set firewall ipv4 output filter default-action 'accept'
set firewall ipv4 output filter rule 1 action 'accept'
set firewall ipv4 output filter rule 1 state established 'enable'
set firewall ipv4 output filter rule 2 action 'drop'
set firewall ipv4 output filter rule 2 state invalid 'enable'
set firewall ipv4 output filter rule 3 action 'accept'
set firewall ipv4 output filter rule 3 state related 'enable'
set firewall ipv4 output filter rule 101 action 'jump'
set firewall ipv4 output filter rule 101 jump-target 'local-guest'
set firewall ipv4 output filter rule 101 outbound-interface interface-group 'IG_guest'
set firewall ipv4 output filter rule 106 action 'jump'
set firewall ipv4 output filter rule 106 jump-target 'local-homelab'
set firewall ipv4 output filter rule 106 outbound-interface interface-group 'IG_homelab'
set firewall ipv4 output filter rule 111 action 'jump'
set firewall ipv4 output filter rule 111 jump-target 'local-iot'
set firewall ipv4 output filter rule 111 outbound-interface interface-group 'IG_iot'
set firewall ipv4 output filter rule 116 action 'jump'
set firewall ipv4 output filter rule 116 jump-target 'local-lan'
set firewall ipv4 output filter rule 116 outbound-interface interface-group 'IG_lan'
set firewall ipv4 output filter rule 121 action 'jump'
set firewall ipv4 output filter rule 121 jump-target 'local-servers'
set firewall ipv4 output filter rule 121 outbound-interface interface-group 'IG_servers'
set firewall ipv4 output filter rule 126 action 'jump'
set firewall ipv4 output filter rule 126 jump-target 'local-services'
set firewall ipv4 output filter rule 126 outbound-interface interface-group 'IG_services'
set firewall ipv4 output filter rule 131 action 'jump'
set firewall ipv4 output filter rule 131 jump-target 'local-staging'
set firewall ipv4 output filter rule 131 outbound-interface interface-group 'IG_staging'
set firewall ipv4 output filter rule 136 action 'jump'
set firewall ipv4 output filter rule 136 jump-target 'local-trusted'
set firewall ipv4 output filter rule 136 outbound-interface interface-group 'IG_trusted'
set firewall ipv4 output filter rule 141 action 'jump'
set firewall ipv4 output filter rule 141 jump-target 'local-wan'
set firewall ipv4 output filter rule 141 outbound-interface interface-group 'IG_wan'
set firewall ipv4 output filter rule 146 action 'drop'
