#!/bin/sh
# This script is executed at boot time before VyOS configuration is applied.
# Any modifications required to work around unfixed bugs or use
# services not available through the VyOS CLI system can be placed here.

# Fix for 1Password containers requiring a user/group id of 999
# and Vyos not preserving file perms on upgrade
mkdir -p /tmp/onepassword/data
chown -R 999:999 /tmp/onepassword
